---

global_role_java: true
global_role_cs_studio: true
global_role_phoebus: true
global_role_sirius_bbb: true
global_role_octave: true
global_role_epics_mca: true
global_role_desktop_settings: true
global_role_visual_studio_code: true

# === apt packages versions ===

pkg_version_zabbix_agent: "1:4.0.3*"
pkg_version_network_manager: "1.14.6*"
pkg_version_python_dbus: "1.2.4*"
pkg_version_python3_dbus: "1.2.4*"
pkg_version_libnm0: "1.14.6*"
pkg_version_autofs: "5.1.2*"
pkg_version_build_essential: "12.3*"
pkg_version_cups: "2.2.1*"
pkg_version_dconf_cli: "0.26.0*"
pkg_version_dmz_cursor_theme: "0.4.4*"
pkg_version_epics_dev: "3.15.6*"
pkg_version_epics_pcas_dev: "3.15.6*"
pkg_version_htop: "2.0.2*"
pkg_version_ipython3: "5.1.0*"
pkg_version_gconf2: "3.2.6*"
pkg_version_git: "1:2.11.0*"
pkg_version_make: "4.1*"
pkg_version_bzip2: "1.0.6*"
pkg_version_binutils: "2.28*"
pkg_version_re2c: "0.16-2*"
pkg_version_automake: "1:1.15*"
pkg_version_autoconf: "2.69*"
pkg_version_libtool: "2.4.6*"
pkg_version_gplusplus: "4:6.3.0*"
pkg_version_curl: "7.52.1*"
pkg_version_libglib2_0_0: "2.50.3*"
pkg_version_libglib2_0_dev: "2.50.3*"
pkg_version_uuid_dev: "2.29.2*"
pkg_version_libreadline7: "7.0*"
pkg_version_libusb_1_0_0_dev: "2:1.0.21*"
pkg_version_libbz2_dev: "1.0.6*"
pkg_version_libxml2_dev: "2.9.4*"
pkg_version_perl: "5.24.1*"
pkg_version_libextutils_cchecker_perl: "0.10*"
pkg_version_libextutils_f77_perl: "1.20*"
pkg_version_libextutils_libbuilder_perl: "0.08*"
pkg_version_libextutils_pkgconfig_perl: "1.15*"
pkg_version_libextutils_xsbuilder_perl: "0.28*"
pkg_version_libextutils_xspp_perl: "0.1800*"
pkg_version_gvncviewer: "0.6.0*"
pkg_version_libasound2: "1.1.3*"
pkg_version_libc6_dev: "2.24*"
pkg_version_apt_setuptools: "33.1.1*"
pkg_version_wmctrl: "1.07*"
pkg_version_libdbus_1_3: "1.10.*"
pkg_version_libffi6: "3.2.1*"
pkg_version_libffi_dev: "3.2.1*"
pkg_version_libfreetype6: "2.6.3*"
pkg_version_libfreetype6_dev: "2.6.3*"
pkg_version_libfontconfig1: "2.11.0*"
pkg_version_libgdbm_dev: "1.8.3*"
pkg_version_libglu1_mesa_dev: "9.0.0*"
pkg_version_libgtk2_0_0: "2.24*"
pkg_version_libncursesw5_dev: "6.0+20161126*"
pkg_version_libqt5opengl5_dev: "5.7.1*"
pkg_version_libreadline5: "5.2*"
pkg_version_libreadline_dev: "7.0*"
pkg_version_libsqlite3_dev: "3.16.2*"
pkg_version_libssl_dev: "1.1.0*"
pkg_version_libxss1: "1:1.2.2*"
pkg_version_nfs_common: "1:1.3.4*"
pkg_version_nfs_kernel_server: "1:1.3.4*"
pkg_version_nmap: "7.40*"
pkg_version_ntp: "1:4.2.8*"
pkg_version_nvidia_driver: "390.116*"
pkg_version_nvidia_kernel_dkms: "390.116*"
pkg_version_openjdk_11_jdk: "11.0.*"
pkg_version_openjfx: "8u141*"
pkg_version_python3_dev: "3.5.3*"
pkg_version_python3_pip: "9.0.1*"
pkg_version_python3_pyqt5_qtsvg: "5.7*"
pkg_version_python3_tk: "3.5.3*"
pkg_version_python_pip: "9.0.1*"
pkg_version_libgsl2: "2.3*"
pkg_version_libblas_dev: "3.7*"
pkg_version_liblapack_dev: "3.7*"
pkg_version_libgsl_dev: "2.3*"
pkg_version_rsync: "3.1.2*"
pkg_version_qt5_default: "5.7.1*"
pkg_version_qtbase5_dev: "5.7.1*"
pkg_version_qttools5_dev_tools: "5.7.1*"
pkg_version_qt5_qmake: "5.7.1*"
pkg_version_sip_dev: "4.18.1*"
pkg_version_tk_dev: "8.6*"
pkg_version_swig: "3.0*"
pkg_version_sshpass: "1.06*"
pkg_version_xfce4: "4.12*"
pkg_version_xfce4_goodies: "4.12*"
pkg_version_remmina: "1.3.3*"
pkg_version_remmina_plugin_rdp: "1.3.3*"
pkg_version_remmina_plugin_secret: "1.3.3*"
pkg_version_vim: "2:8.0*"
pkg_version_tightvncserver: "1:1.3.9*"
pkg_version_rdesktop: "1.8.6*"
pkg_version_unzip: "6.0*"
pkg_version_openjdk_8_jdk: "8u222-b10*"
pkg_version_openjdk_8_jre: "8u222-b10*"
pkg_version_xcursor_themes: "1.0.4*"
pkg_version_x11_common: "1:7.7*"
pkg_version_epics_extensions_dev: "20130514.5*"
pkg_version_edm_dev: "1.12.105B*"
pkg_version_gnome_terminal: "3.22.2*"
pkg_version_xpra: "0.17.6*"
pkg_version_winswitch: "0.12.21*"
pkg_version_xvfb: "2:1.19.2*"
pkg_version_bc: "1.06.95*"
pkg_version_wait_for_it: "0.0*"
pkg_version_octave: "4.0.3*"
pkg_version_liboctave_dev: "4.0.3*"
pkg_version_epstool: "3.08*"
pkg_version_texlive_latex_recommended: "2016.20170123*"
pkg_version_dvipng: "1.14*"
pkg_version_ghostscript: "9.26*"
pkg_version_libxcb_dri3_0: "1.14*"
pkg_version_libdrm2: "2.4.74*"
pkg_version_libgbm1: "13.0.6*"


# === pip packages ===

pkg_version_pip: "19.3.1"
pkg_version_python_dateutil: "2.8.1"
pkg_version_cairocffi: "1.1.0"
pkg_version_jupyter: "1.0.0"
pkg_version_jupyter_nbextensions: "0.5.1"
pkg_version_six: "1.13.0"
pkg_version_numpy: "1.18"
pkg_version_bottleneck: "1.3"
pkg_version_pylama: "7.6.6"
pkg_version_pep8: "1.7.1"
pkg_version_autopep8: "1.4.3"
pkg_version_pydocstyle: "4.0.1"
pkg_version_pylint: "2.3.1"
pkg_version_matplotlib: "3.1.2"
pkg_version_pandas: "0.25.3"
pkg_version_pcaspy: "0.7.2"
pkg_version_psutil: "5.6.7"
pkg_version_pyepics: "3.4.0"
pkg_version_pyqtgraph: "0.11.0"
pkg_version_python_nmap: "0.6.1"
pkg_version_requests: "2.22.0"
pkg_version_scipy: "1.4.1"
pkg_version_setuptools: "44.0.0"
pkg_version_sh: "1.12.14"
pkg_version_termcolor: "1.1.0"
pkg_version_wakeonlan: "1.1.6"
pkg_version_xlrd: "1.2.0"
pkg_version_PyQt5: "5.11.3"
pkg_version_PyQt5_sip: "12.7.0"
pkg_version_pydm: "1.10.2"
pkg_version_timechart: "1.2.2"
pkg_version_qtawesome: "0.7.2"
pkg_version_pyvisa: "1.10.1"
pkg_version_pyvisa_py: "0.3.1"
