---
__qt_install_from_src: false

__pyqt_install_from_src: false

__pyqt_dep_packages:
  - liblapack-dev
  - libdbus-1-3
  - libglu1-mesa-dev
  - libffi6
  - libffi-dev
  - libfreetype6
  - libfreetype6-dev

__qt_distro_packages:
  - qt5-default
  - qttools5-dev-tools
  - sip-dev
  - python3-pyqt5.qtsvg
  - libqt5opengl5-dev
  - qt5-qmake
  - qtbase5-dev

__qt_pip_packages:
  - PyQt5
  - PyQt5-sip

__python_executable: python-sirius

__pip_executable: pip-sirius
