---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install Java packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie
    - name: Ubuntu
      versions:
        - xenial
        - trusty

dependencies: []
