---
# Package versions for Debian. Leave empty for the latest
pkg_version_edm_dev: ""
pkg_version_xpra: ""
pkg_version_xvfb: ""
pkg_version_gnome_terminal: ""
pkg_version_qtawesome: ""

# package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_hla_packages_state: present

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_apps_hla_pip_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
sirius_apps_hla_install_recommends: true

# Sirius Linac EDM screens
sirius_apps_hla_li_edm_dir: /usr/local/share/edm/data

# Sirius designer path
sirius_apps_hla_designer_dir: /usr/local/share/Qt/designer

# Groups of packages
# Example
#
# sirius_apps_hla_packages_group_1:
#  - name: High-Level Applications
#    org_url: https://github.com/lnls-sirius
#    repo_name: hla
#    repo_version: master
#    clone_path: /tmp
#    install_chdir: pyqt-apps
#    install_via_makefile: true
#    make_install_target: install-all
#    make_install_opts:
#      INSTALL_DESIGNER_DIR: "{{ sirius_apps_hla_designer_dir }}"
#    force_version: true
#
# sirius_apps_hla_packages_group_2:
#   - name: OPIs
#     org_url: https://gitlab.cnpem.br/FACS
#     repo_name: linac-opi
#     repo_version: master
#     clone_path: /tmp
#     install_via_makefile: true
#     make_install_target: install-default
#     make_install_opts:
#       INSTALL_EDM_DIR: "{{ sirius_apps_hla_li_edm_dir }}"
#     force_version: true
#     ssl_no_verify: true
#
# sirius_apps_hla_install_categories:
#   - sirius_apps_hla_packages_group_1
#   - sirius_apps_hla_packages_group_2
#
sirius_apps_hla_packages_group_1: []

sirius_apps_hla_packages_group_2: []

# Select which categories to install
sirius_apps_hla_install_categories:
  - sirius_apps_hla_packages_group_1
  - sirius_apps_hla_packages_group_2

sirius_apps_hla_config_files:
  - name: Sirius HLA environment variables
    filename: sirius_hla.sh
    pathname: "/etc/profile.d"

  - name: Sirius Apps Linac EDM variables
    filename: linac_edm.sh
    pathname: "/etc/profile.d"
