---
galaxy_info:
  author: Claudio Carneiro
  description: Ansible role to install python packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - stretch

dependencies: []
