---
- name: Install additional software packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"

- name: Remove specified software packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remove_packages }}"
