---
- hosts: bbb
  remote_user: fac
  become: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  tasks:
    - name: Check out eth-bridge-pru-serial485
      git:
        repo: 'https://github.com/lnls-sirius/eth-bridge-pru-serial485'
        dest: /root/eth-bridge-pru-serial485
        version: "{{ pkg_version_ethbridge_pru_serial }}"
    - name: Check out pru-serial485
      git:
        repo: 'https://github.com/lnls-sirius/pru-serial485'
        dest: /root/pru-serial485
        version: "{{ pkg_version_pru_serial }}"
        force: true
    - name: Install pru-serial485
      make:
        chdir: /root/pru-serial485/src/
        target: install
    - name: Install eth-bridge-pru-serial485
      make:
        chdir: /root/eth-bridge-pru-serial485/server/
        target: install
