---
- hosts: control_room:control_room_TV:linac_opi:control_room_nvidia_false:con:elp
  remote_user: sirius
  become: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  roles:
    - role: lnls-ans-role-repositories
    - role: lnls-ans-role-users
      when: global_role_users | default(true) | bool
    - role: lnls-ans-role-network
      when: global_network_role | default(true) | bool
    - role: lnls-ans-role-nvidia-driver
      when: global_import_nvidia_driver_role | default(false) | bool
    - role: lnls-ans-role-ntp
    - role: lnls-ans-role-nfsclient
    - role: lnls-ans-role-zabbix
    - role: lnls-ans-role-python
    - role: lnls-ans-role-epics
    - role: lnls-ans-role-epics7
    - role: lnls-ans-role-qt
    - role: lnls-ans-role-java
      when: global_role_java | default(true) | bool
    - role: lnls-ans-role-cs-studio
      when: global_role_cs_studio | default(true) | bool
    - role: lnls-ans-role-pydm
    - role: lnls-ans-role-phoebus
      when: global_role_phoebus | default(true) | bool
    - role: lnls-ans-role-sirius-bbb
      when: global_role_sirius_bbb | default(true) | bool
    - role: lnls-ans-role-octave
      when: global_role_octave | default(true) | bool
    - role: lnls-ans-role-epics-mca
      when: global_role_epics_mca | default(true) | bool
    - role: lnls-ans-role-conda
    - role: lnls-ans-role-sirius-hlacon
    - role: lnls-ans-role-sirius-apps
    - role: lnls-ans-role-sirius-hla
    - role: lnls-ans-role-desktop-apps
    - role: lnls-ans-role-desktop-settings
      when: global_role_desktop_settings | default(true) | bool
    - role: lnls-ans-role-visual-studio-code
      when: global_role_visual_studio | default(false) | bool
