---
- hosts: web_servers
  remote_user: sirius
  become: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ lookup('first_found', possible_var_files, errors='ignore') }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"

  tasks:
    - import_role:
        name: lnls-ans-role-users
    - import_role:
        name: lnls-ans-role-nfsserver
    - import_role:
        name: lnls-ans-role-clone-install
      vars:
        clone_install_repos: "{{ lookup('vars', 'clone_install_repos_servweb', default=[]) }}"
