---
galaxy_info:
  author: Fernando H. de SÃ¡
  description: Ansible role to install PyDM Package
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.6

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

dependencies:
  - lnls-ans-role-python
  - lnls-ans-role-epics
# - lnls-ans-role-qt
