---
# Install from source
__python_install_from_src: true

__basic_packages:
  - git
  - build-essential

__python_dep_packages:
  - libreadline-dev
  - libreadline5
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev

__python_base_packages:
  - python3-dev

__python_packages:
  - python3-pip
  - python3-tk
  # - python-setuptools
  - swig

__pip_executable: pip-sirius

__python_pip_packages:
  - cairocffi
  - jupyter
  - setuptools
  - matplotlib
  - pandas
  - psutil
  - pyqtgraph
  - python-nmap
  - requests
  - scipy
  - sh
  - termcolor
  - wakeonlan
  - xlrd
