---
# Install from source
__python_install_from_src: false

__basic_packages:
  - "git={{ pkg_version_git }}"
  - "build-essential={{ pkg_version_build_essential }}"

__python_dep_packages:
  - "libreadline5={{ pkg_version_libreadline5 }}"
  - "libreadline-dev={{ pkg_version_libreadline_dev }}"
  - "libncursesw5-dev={{ pkg_version_libncursesw5_dev }}"
  - "libssl-dev={{ pkg_version_libssl_dev }}"
  - "libsqlite3-dev={{ pkg_version_libsqlite3_dev }}"
  - "tk-dev=8.6.9+1*"
  - "libgdbm-dev={{ pkg_version_libgdbm_dev }}"
  - "libc6-dev={{ pkg_version_libc6_dev }}"
  - "libbz2-dev={{ pkg_version_libbz2_dev }}"


__python_base_packages:
  - "python3-dev={{ pkg_version_python3_dev }}"

# We may need to install python2 setuptools because of ansible issue:
# https://github.com/ansible/ansible/issues/47361
__python_packages:
  - "python3-pip={{ pkg_version_python3_pip }}"
  - "python3-tk={{ pkg_version_python3_tk }}"
  - "python-setuptools={{ pkg_version_apt_setuptools }}"
  - "swig=3.0.12*"

__pip_executable: pip-sirius

__python_pip_packages:
  - "python-dateutil=={{ pkg_version_python_dateutil }}"
  - "cairocffi=={{ pkg_version_cairocffi }}"
  - "jupyter=={{ pkg_version_jupyter }}"
  - "jupyter-contrib-nbextensions=={{ pkg_version_jupyter_nbextensions }}"
  - "numpy=={{ pkg_version_numpy }}"
  - "six=={{ pkg_version_six }}"
  - "pylama=={{ pkg_version_pylama }}"
  - "pep8=={{ pkg_version_pep8 }}"
  - "autopep8=={{ pkg_version_autopep8 }}"
  - "pydocstyle=={{ pkg_version_pydocstyle }}"
  - "pylint=={{ pkg_version_pylint }}"
  - "setuptools=={{ pkg_version_setuptools }}"
  - "matplotlib=={{ pkg_version_matplotlib }}"
  - "pandas=={{ pkg_version_pandas }}"
  - "psutil=={{ pkg_version_psutil }}"
  - "pyqtgraph=={{ pkg_version_pyqtgraph }}"
  - "python-nmap=={{ pkg_version_python_nmap }}"
  - "requests=={{ pkg_version_requests }}"
  - "scipy=={{ pkg_version_scipy }}"
  - "sh=={{ pkg_version_sh }}"
  - "termcolor=={{ pkg_version_termcolor }}"
  - "wakeonlan=={{ pkg_version_wakeonlan }}"
  - "xlrd=={{ pkg_version_xlrd }}"
