---
# Package versions for Debian. Leave empty for the latest
pkg_version_liblapack_dev: ""
pkg_version_libdbus_1_3: ""
pkg_version_libglu1_mesa_dev: ""
pkg_version_libffi6: ""
pkg_version_libffi_dev: ""
pkg_version_libfreetype6: ""
pkg_version_libfreetype6_dev: ""
pkg_version_libfontconfig1: ""
pkg_version_libxkbcommon_dev: ""
pkg_version_libxkbcommon_x11_dev: ""
pkg_version_qt5_default: ""
pkg_version_qttools5_dev_tools: ""
pkg_version_sip_dev: ""
pkg_version_python3_pyqt5_qtsvg: ""
pkg_version_libqt5opengl5_dev: ""
pkg_version_qt5_qmake: ""
pkg_version_qtbase5_dev: ""
pkg_version_PyQt5: ""
pkg_version_PyQt5_sip: ""

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
qt_pip_packages_state: present

#############################
# Qt variables
#############################

# If true, Qt source for the version will be downloaded and
# installed again even if it's found on the system.
qt_src_force_install: false

# Qt source version when installing from source
qt_src_version: 5.13.1

# Qt script checksum. Extracted from website
qt_src_checksum: md5:21c3b16f851697fa8da8009f73694373

# Qt source script name
qt_src_remote_script: "qt-opensource-linux-x64-{{ qt_src_version }}.run"

# Qt URL downlaod script
qt_src_download_url: "https://download.qt.io/archive/qt/{{ qt_src_version_reduced }}/{{ qt_src_version }}/{{ qt_src_remote_script }}"

qt_src_dir_path: /tmp/Qt

qt_src_dir_install_path: /usr/local/lib/Qt

# Qt binary directory
qt_src_bin_dir: "{{ qt_src_dir_install_path }}/{{ qt_src_version }}/gcc_64/bin"

# Qt plugin directory
qt_src_plugin_dir: "{{ qt_src_dir_install_path }}/{{ qt_src_version }}/gcc_64/plugins"

qt_src_designer_symlink: /usr/local/bin/designer

qt_src_support_install_files:
  - name: Qt noninteractive installation file
    filename: qt-noninteractive.qs
    pathname: "{{ qt_src_dir_path }}"

qt_src_config_files:
  - name: Qt environment variables
    filename: qt.sh
    pathname: "/etc/profile.d"

#############################
# PyQt SIP variables
#############################

# PyQt SIP source version when installing from source
pyqt_sip_src_version: 4.19.24

pyqt_sip_src_dir_name: "sip-{{ pyqt_sip_src_version }}"

# pyQt SIP source script name
pyqt_sip_src_remote_script: "{{ pyqt_sip_src_dir_name }}.tar.gz"

pyqt_sip_src_download_url: "https://www.riverbankcomputing.com/static/Downloads/sip/{{ pyqt_sip_src_version }}/{{ pyqt_sip_src_remote_script }}"

pyqt_sip_src_dir_path: /tmp/pyQt-sip

pyqt_sip_src_dir: "{{ pyqt_sip_src_dir_path }}/{{ pyqt_sip_src_dir_name }}"

#############################
# PyQt variables
#############################

# If true, the pyQt and pyQt Sip source for the version will be downloaded and
# installed again even if it's found on the system.
pyqt_src_force_install: false

# pyQt source version when installing from source
pyqt_src_version: 5.13.1

# pyQt source script name
pyqt_src_dir_name: "PyQt5_gpl-{{pyqt_src_version }}"

# pyQt source script name
pyqt_src_remote_script: "{{ pyqt_src_dir_name }}.tar.gz"

# pyQt URL downlaod script
pyqt_src_download_url: "https://www.riverbankcomputing.com/static/Downloads/PyQt5/{{ pyqt_src_version }}/{{ pyqt_src_remote_script }}"

pyqt_src_dir_path: /tmp/pyQt

pyqt_src_dir: "{{ pyqt_src_dir_path }}/{{ pyqt_src_dir_name }}"

#############################
# pyQt Apps
#############################

pyqt_apps:
  - name: "PyQt SIP"
    download_url: "{{ pyqt_sip_src_download_url }}"
    src_dir_path: "{{ pyqt_sip_src_dir_path }}"
    src_dir: "{{ pyqt_sip_src_dir }}"
    cfg_command: >-
      {{ python_executable }} configure.py
      --sip-module=PyQt5.sip
    cfg_force: true
    make_build_target: -j4
    make_build_opts: {}
    make_install_target: install
    make_install_opts: {}

  - name: "PyQt"
    download_url: "{{ pyqt_src_download_url }}"
    src_dir_path: "{{ pyqt_src_dir_path }}"
    src_dir: "{{ pyqt_src_dir }}"
    cfg_create_paths: "{{ qt_src_plugin_dir }}/PyQt5"
    cfg_command: >-
      {{ python_executable }} configure.py
        --qmake={{ qt_src_bin_dir }}/qmake
        --designer-plugindir={{ qt_src_plugin_dir }}/designer
        --qml-plugindir={{ qt_src_plugin_dir }}/PyQt5
        --confirm-license
        --assume-shared
    cfg_force: false
    make_build_target: -j4
    make_build_opts: {}
    make_install_target: install
    make_install_opts: {}
