---
galaxy_info:
  author: Ximenes Resende
  description: Ansible role to install Sirius HLA Apps packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

dependencies:
  - lnls-ans-role-repositories
  - lnls-ans-role-users
  - lnls-ans-role-epics
