---
- hosts: gluster_servers docker_servers
  remote_user: server
  become: true
  become_method: su
  become_user: root

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "group_vars/{{ ansible_distribution }}.yml"
          - "group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"
    
  roles:
    - { role: lnls-ans-role-ntp, when: ansible_os_family == "Debian" }

  tasks:
    - name: "Adding existing user {{ ansible_ssh_user }} to group sudo"
      user:
        name: "{{ ansible_ssh_user }}"
        groups: sudo
        append: yes
      when:
        - ansible_os_family == 'Debian'

    - name: "Adding existing user {{ ansible_ssh_user }} to group wheel"
      user:
        name: "{{ ansible_ssh_user }}"
        groups: wheel
        append: yes
      when:
        - ansible_os_family == 'RedHat'

    - name: sudo
      apt:
        name: sudo
        state: latest
        update_cache: yes

    - name: "Neovim dir"
      file:
        path: /opt/nvim
        state: directory
        mode: "0755"

    - name: "Check nvim.appimage"
      stat:
        path: /opt/nvim/nvim.appimage
      register: stat_result

    - name: "Download Neovim"
      get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: /opt/nvim/nvim.appimage
        mode: '0555'
      when: not stat_result.stat.exists

    - name: "Create symbolic link"
      file:
        src: "/opt/nvim/nvim.appimage"
        dest: "/usr/local/bin/nvim"
        state: link
