---
__network_packages:
  - "network-manager{{ (pkg_version_network_manager | length > 0) | ternary('=' + pkg_version_network_manager, '') }}"
  - "python3-dbus{{ (pkg_version_python3_dbus  | length > 0) | ternary('=' + pkg_version_python3_dbus, '') }}"
  - "libnm0{{ (pkg_version_libnm0  | length > 0) | ternary('=' + pkg_version_libnm0, '') }}"

__network_default_release: stretch-backports
