---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install Control System Studio
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

dependencies:
  # - lnls-ans-role-java
  # - lnls-ans-role-python
  # - lnls-ans-role-phoebus
