---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install Control System Studio
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

dependencies:
  - lnls-ans-role-repositories
# - lnls-ans-role-python
