---
__desktop_packages:
  - "rdesktop=1.8.6*"
  - "htop={{ pkg_version_htop }}"
  - "vim=2:8.1.0875*"
  - "ipython3={{ pkg_version_ipython3 }}"
  - "remmina=1.3.3*"
  - "remmina-plugin-rdp=1.3.3*"
  - "remmina-plugin-secret=1.3.3*"
  - "tightvncserver=1:1.3.9*"
  - "gvncviewer={{ pkg_version_gvncviewer }}*"
  - "xfce4=4.12.5*"
  - "xfce4-goodies=4.12.6*"
  - "wmctrl={{ pkg_version_wmctrl }}"
  - "cups={{ pkg_version_cups }}"
  - "ca-certificates={{ pkg_version_ca_certificates }}"
  - "gconf2={{ pkg_version_gconf2 }}"
  - "libasound2={{ pkg_version_libasound2 }}"
  - "libgtk2.0-0={{ pkg_version_libgtk2_0_0 }}"
  - "libxss1={{ pkg_version_libxss1 }}"
  - "libffi6={{ pkg_version_libffi6 }}"
  - "libffi-dev={{ pkg_version_libffi_dev }}"
  - "libfreetype6={{ pkg_version_libfreetype6 }}"
  - "libfreetype6-dev={{ pkg_version_libfreetype6_dev }}"
  - "nmap={{ pkg_version_nmap }}"
  - "dvipng={{ pkg_version_dvipng }}"
  - "sshpass"
  - "wait-for-it"
  - "libgsl2={{ pkg_version_libgsl2 }}"
  - "libgsl-dev={{ pkg_version_libgsl_dev }}"

__desktop_pip_packages:
  - "python-nmap=={{ pkg_version_python_nmap }}"
  - "wakeonlan=={{ pkg_version_wakeonlan }}"
  - "requests=={{ pkg_version_requests }}"
  - "pyqtgraph=={{ pkg_version_pyqtgraph }}"
  - "pandas=={{ pkg_version_pandas }}"
  - "psutil=={{ pkg_version_psutil }}"
  - "termcolor=={{ pkg_version_termcolor }}"
  - "sh=={{ pkg_version_sh }}"
  - "cairocffi=={{ pkg_version_cairocffi }}"
  - "matplotlib=={{ pkg_version_matplotlib }}"
  - "scipy=={{ pkg_version_scipy }}"
  - "jupyter=={{ pkg_version_jupyter }}"
  - "xlrd=={{ pkg_version_xlrd }}"

__pip_executable: pip-sirius
