---
__desktop_packages:
  - rdesktop
  - htop
  - vim
  - ipython3
  - remmina
  - remmina-plugin-rdp
  - remmina-plugin-secret
  - tightvncserver
  - gvncviewer
  - xfce4
  - xfce4-goodies
  - wmctrl
  - cups
  - ca-certificates
  - gconf2
  - libasound2
  - libgtk2.0-0
  - libxss1
  - libffi6
  - libffi-dev
  - libfreetype6
  - libfreetype6-dev
  - nmap
  - sshpass
  - wait-for-it
  - libgsl23
  - libgsl-dev
  - texlive-latex-recommended
  - dvipng
  - ghostscript

__desktop_pip_packages:
  - python-nmap
  - wakeonlan
  - requests
  - pyqtgraph
  - pandas
  - psutil
  - termcolor
  - sh
  - cairocffi
  - matplotlib
  - scipy
  - jupyter
  - xlrd

__pip_executable: pip-sirius
