---
__octave_packages:
  - "octave{{ (pkg_version_octave | length > 0) | ternary('=' + pkg_version_octave, '') }}"
  - "liboctave-dev{{ (pkg_version_liboctave_dev | length > 0) | ternary('=' + pkg_version_liboctave_dev, '') }}"
  - "epstool{{ (pkg_version_epstool | length > 0) | ternary('=' + pkg_version_epstool, '') }}"
