---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Install dependencies (rsync)
  apt:
    name: rsync
    state: present

- name: Ensure Sirius BbB packages are installed
  apt:
    name: "{{ sirius_bbb_packages }}"
    state: "{{ sirius_bbb_packages_state }}"
    install_recommends: "{{ sirius_bbb_install_recommends }}"
  become: true
  register: apt_packages_result
  until: apt_packages_result is success
  retries: 5
  delay: 2

- name: Ensure Sirius BbB Python packages are installed
  pip:
    name: "{{ sirius_bbb_pip_packages }}"
    state: "{{ sirius_bbb_pip_packages_state }}"
    executable: "{{ pip_executable }}"
  become: true
  register: pip_packages_result
  when: sirius_bbb_pip_packages | length > 0
  until: pip_packages_result is success
  retries: 5
  delay: 2
