---
- name: "Create {{ item.name }} installation directory"
  file:
    path: "{{ item.src_dir_path }}"
    state: directory

- name: "Download {{ item.name }}"
  unarchive:
    src: "{{ item.download_url }}"
    dest: "{{ item.src_dir_path }}"
    remote_src: true
    owner: root
    group: root
    creates: "{{ item.src_dir }}"
  register: download_item_result
  become: true

- name: "Create {{ item.name }} needed installation paths"
  file:
    path: "{{ item.cfg_create_paths }}"
    state: directory
  when:
    - item.cfg_create_paths is defined and
      item.cfg_create_paths | length > 0

- name: "Configure {{ item.name }}" 
  command: "{{ item.cfg_command }}"
  args:
    chdir: "{{ item.src_dir }}"

- name: "Build {{ item.name }} via Makefile"
  make:
    chdir: "{{ item.src_dir }}"
    target: "{{ item.make_build_target | default(omit) }}" 
    params: "{{ item.make_build_opts | default({}) }}"

- name: "Install {{ item.name }} via Makefile"
  make:
    chdir: "{{ item.src_dir }}"
    target: "{{ item.make_install_target | default(omit) }}" 
    params: "{{ item.make_install_opts | default({}) }}"
  become: true
