---
# Package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_bbb_packages_state: present

# PIP package state; use 'present' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
sirius_bbb_pip_packages_state: present

# Whether to install recommended packages. Used only for Debian/Ubuntu.
sirius_bbb_install_recommends: true

# Repository version
sirius_bbb_version: master

# Sirius BBB EDM screens
sirius_bbb_edm_dir: /usr/local/share/edm/data/bbb

# Sirius BBB bin destination directories
sirius_bbb_bin_dir: /usr/local/bin

# Sirius BBB config destination directories
sirius_bbb_cfg_dir: /usr/local/share/bbb

# Sirius BBB IGPTOP variable
sirius_bbb_igp_top_dir: "{{ sirius_bbb_edm_dir }}"

# Groups of packages
sirius_bbb_opis:

  - name: OPIs
    org_url: https://gitlab.cnpem.br/DIG
    repo_name: bbb-igp12-sw
    repo_version: "{{ sirius_bbb_version | default(master) }}"
    clone_path: /tmp
    install_via_makefile: true
    make_install_target: install
    make_install_opts:
      INSTALL_EDM_DIR: "{{ sirius_bbb_edm_dir }}"
      INSTALL_BIN_DIR: "{{ sirius_bbb_bin_dir }}"
      INSTALL_EDM_CFG_DIR: "{{ sirius_bbb_cfg_dir }}"
    force_version: true
    environment:
      GIT_SSL_NO_VERIFY: true

# Select which categories to install. Defaults to all
sirius_bbb_install_categories:
  - sirius_bbb_opis

sirius_bbb_config_files:
  - name: Sirius BbB environment variables
    filename: sirius_bbb.sh
    pathname: "/etc/profile.d"

  - name: Sirius BbB launcher script
    mode: "0755"
    filename: sirius-hla-bbb-launcher.sh
    pathname: "{{ sirius_bbb_bin_dir }}"
