---
- name: Install python packages
  apt:
    name: "{{ python_all }}"
    state: present
  become: true
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 2

- name: Check which python version is installed
  command: "which {{ python_exec }}"
  register: python_check_result
  changed_when: false
  check_mode: false

- name: Check which pip version is installed
  command: "which {{ pip_exec }}"
  register: pip_check_result
  changed_when: false
  check_mode: false

- name: Check which python-config version is installed
  command: "which {{ python_config_exec }}"
  register: python_config_check_result
  changed_when: false
  check_mode: false

- name: Install python symlink
  file:
    src: "{{ python_check_result.stdout }}"
    dest: "{{ python_symlink }}"
    state: link
  become: true

- name: Install PIP symlink
  file:
    src: "{{ pip_check_result.stdout }}"
    dest: "{{ pip_symlink }}"
    state: link
  become: true

- name: Install python-config symlink
  file:
    src: "{{ python_config_check_result.stdout }}"
    dest: "{{ python_config_symlink }}"
    state: link
  become: true

- name: Install Python PIP packages
  pip:
    name: "{{ python_pip_packages }}"
    state: present
    executable: "{{ pip_executable }}"
  become: true
  register: python_pip_packages_result
  until: python_pip_packages_result is success
  retries: 5
  delay: 2
