- name: Ensure PyDM environment file is installed
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
    owner: root
    group: root
    force: true
    mode: 0644
  become: true
  with_items:
    - "{{ pydm_config_files }}"

- name: Install PyDM
  pip:
    name: "pydm{{ (pkg_version_pydm | length > 0) | ternary('==' + pkg_version_pydm, '') }}"
    state: "{{ pydm_state }}"
    executable: "{{ pip_executable }}"
  become: true
  register: pydm_result
  until: pydm_result is success
  retries: 5
  delay: 2

- name: Install Recommended PIP packages
  pip:
    name: "{{ pydm_recommended_apps_pip }}"
    state: "present"
    executable: "{{ pip_executable }}"
  become: true
  register: pydm_recommended_apps_result
  when: pydm_recommended_apps_pip_install is defined and
        (pydm_recommended_apps_pip_install | bool)
  until: pydm_recommended_apps_result is success
  retries: 5
  delay: 2
