---
- name: Ensure Pip Python (default system python) packages are installed
  pip:
    name: "{{ desktop_settings_pip_packages }}"
    state: "{{ desktop_settings_pip_packages_state }}"
    executable: pip2
  become: true
  register: desktop_settings_pip_packages_result
  until: desktop_settings_pip_packages_result is success
  retries: 5
  delay: 2

- name: Ensure cursor is updated
  alternatives:
    name: x-cursor-theme
    path: "{{ desktop_settings_cursor_theme_alternative }}"
  become: true

- name: Add cursor size to Xresources
  lineinfile:
    state: present
    path: /etc/X11/Xresources/x11-common
    line: "{{ item }}"
    insertafter: EOF
  become: true
  with_items:
    - "{{ desktop_settings_xresources_lines | default([]) }}"

# Workaround for ansible issue #23530
# https://github.com/ansible/ansible/issues/23530
- name: Set localuser for ansible, workaround for \#23530 issue
  set_fact:
    localuser: "{{ ansible_user }}"

- name: Ensure cursor size is set go DConf
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(present) }}"
  become: true
  become_user: "{{ localuser }}"
  with_items:
    - "{{ desktop_settings_dconf_lines }}"
