---
- hosts: ioc_as_ps_dclinks_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service
    services_to_run:
      - sirius-ioc-as-ps-dclink-ia01.service
      - sirius-ioc-as-ps-dclink-ia02.service
      - sirius-ioc-as-ps-dclink-ia03.service
      - sirius-ioc-as-ps-dclink-ia04.service
      - sirius-ioc-as-ps-dclink-ia05.service
      - sirius-ioc-as-ps-dclink-ia06.service
      - sirius-ioc-as-ps-dclink-ia07.service
      - sirius-ioc-as-ps-dclink-ia08.service
      - sirius-ioc-as-ps-dclink-ia09.service
      - sirius-ioc-as-ps-dclink-ia10.service
      - sirius-ioc-as-ps-dclink-ia11.service
      - sirius-ioc-as-ps-dclink-ia12.service
      - sirius-ioc-as-ps-dclink-ia13.service
      - sirius-ioc-as-ps-dclink-ia14.service
      - sirius-ioc-as-ps-dclink-ia15.service
      - sirius-ioc-as-ps-dclink-ia16.service
      - sirius-ioc-as-ps-dclink-ia17.service
      - sirius-ioc-as-ps-dclink-ia18.service
      - sirius-ioc-as-ps-dclink-ia19.service
      - sirius-ioc-as-ps-dclink-ia20.service
      - sirius-ioc-si-ps-dclink-id-ia09.service

  tasks:
    - name: "Run {{ role_to_run }} role"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "{{ item }}"
      with_items:
        - "{{ services_to_run }}"
