---
__sirius_apps_packages:
  - "epics-extensions-dev{{ (pkg_version_epics_extensions_dev | length > 0) | ternary('=' + pkg_version_epics_extensions_dev, '') }}"
  - "winswitch{{ (pkg_version_winswitch | length > 0) | ternary('=' + pkg_version_winswitch, '') }}"
  - "bc{{ (pkg_version_bc | length > 0) | ternary('=' + pkg_version_bc, '') }}"
  - "libgsl2{{ (pkg_version_libgsl2 | length > 0) | ternary('=' + pkg_version_libgsl2, '') }}"
  - "libblas-dev{{ (pkg_version_libblas_dev | length > 0) | ternary('=' + pkg_version_libblas_dev, '') }}"
  - "liblapack-dev{{ (pkg_version_liblapack_dev | length > 0) | ternary('=' + pkg_version_liblapack_dev, '') }}"
  - "libgsl-dev{{ (pkg_version_libgsl_dev | length > 0) | ternary('=' + pkg_version_libgsl_dev, '') }}"

__sirius_apps_pip_packages:
  - "pyvisa={{ (pkg_version_pyvisa | length > 0) | ternary('=' + pkg_version_pyvisa, '') }}"
  - "pyvisa-py={{ (pkg_version_pyvisa_py | length > 0) | ternary('=' + pkg_version_pyvisa_py, '') }}"

__python_executable: python-sirius

__pip_executable: pip-sirius
