---
- name: Create cons environment
  conda:
    name: python
    version: "{{ sirius_apps_hlacon_conda_python_version }}"
    environment: "{{ sirius_apps_hlacon_conda_environment_path }}"
    state: present
    executable: "{{ conda_mamba_executable }}"

- name: Install conda dependencies
  conda:
    name: "{{ sirius_apps_hlacon_conda_packages }}"
    channels: conda-forge
    environment: "{{ sirius_apps_hlacon_conda_environment_path }}"
    state: present
    executable: "{{ conda_mamba_executable }}"
  register: hlacon_conda_packages_result
  until: hlacon_conda_packages_result is success
  retries: 5
  delay: 2

- name: Install conda dependency PIP packages
  pip:
    name: "{{ sirius_apps_hlacon_pip_dep_packages }}"
    state: "{{ sirius_apps_hlacon_pip_dep_packages_state }}"
    executable: "{{ conda_python_pip_executable }}"
  vars:
    ansible_python_interpreter: "{{ conda_python_executable }}"
  become: true
  register: hlacon_pip_dep_packages_result
  until: hlacon_pip_dep_packages_result is success
  retries: 5
  delay: 2

- name: Clone and install pip packages within cons conda environment
  pip:
    name: "{{ sirius_apps_hlacon_pip_packages }}"
    state: present
    executable: "{{ sirius_apps_hlacon_conda_environment_path }}/bin/pip"
  register: hlacon_pip_packages_result
  until: hlacon_pip_packages_result is success
  retries: 5
  delay: 2

- name: Create siriushlacon shell executables
  template:
    src: siriushlacon.j2
    dest: "/usr/bin/{{ item }}"
    mode: 0755
  with_items:
      - "{{ sirius_apps_hlacon_executables }}"
