---
# Whether to install recommended packages. Used only for Debian/Ubuntu.
pydm_recommended_apps_pip_install: true

# Whether pydm should be present or not
pydm_state: "present"

pydm_config_files:
  - name: PyDM environment variables
    filename: pydm_app.sh
    pathname: "/etc/profile.d"
