---
__epics7_dep_packages:
  - "bzip2={{ pkg_version_bzip2 }}"
  - "binutils={{ pkg_version_binutils }}"
  - "git={{ pkg_version_git }}"
  - "re2c={{ pkg_version_re2c }}"
  - "automake={{ pkg_version_automake }}"
  - "autoconf={{ pkg_version_autoconf }}"
  - "make={{ pkg_version_make }}"
  - "libtool={{ pkg_version_libtool }}"
  - "curl={{ pkg_version_curl }}"
  # Build tools
  - "g++={{ pkg_version_gplusplus }}"
  - "libglib2.0-0={{ pkg_version_libglib2_0_0 }}"
  - "libglib2.0-dev={{ pkg_version_libglib2_0_dev }}"
  - "uuid-dev={{ pkg_version_uuid_dev }}"
  - "libreadline7={{ pkg_version_libreadline7 }}"
  - "libreadline-dev={{ pkg_version_libreadline_dev }}"
  - "libusb-1.0-0-dev={{ pkg_version_libusb_1_0_0_dev }}"
  - "bzip2={{ pkg_version_bzip2 }}"
  - "libbz2-dev={{ pkg_version_libbz2_dev }}"
  - "libxml2-dev={{ pkg_version_libxml2_dev }}"
  - "perl={{ pkg_version_perl }}"
  # Perl dependencies
  - "libextutils-cchecker-perl={{ pkg_version_libextutils_cchecker_perl }}"
  - "libextutils-f77-perl={{ pkg_version_libextutils_f77_perl }}"
  - "libextutils-libbuilder-perl={{ pkg_version_libextutils_libbuilder_perl }}"
  - "libextutils-pkgconfig-perl={{ pkg_version_libextutils_pkgconfig_perl }}"
  - "libextutils-xsbuilder-perl={{ pkg_version_libextutils_xsbuilder_perl }}"
  - "libextutils-xspp-perl={{ pkg_version_libextutils_xspp_perl }}"
