---
__epics7_dep_packages:
  - bzip2=1.0.6*
  - binutils=2.31.1*
  - git=1:2.20.1*
  - re2c=1.1.1*
  - automake=1:1.16.1*
  - autoconf=2.69*
  - make=4.2.1*
  - libtool=2.4.6*
  - curl=7.64.0*
  # Build tools
  - g++=4:8.3.0*
  - libglib2.0-0=2.58.3*
  - libglib2.0-dev=2.58.3*
  - uuid-dev=2.33.1*
  - libreadline7=7.0*
  - libreadline-dev=7.0*
  - libusb-1.0-0-dev=2:1.0.22*
  - bzip2=1.0.6*
  - libbz2-dev=1.0.6*
  - libxml2-dev=2.9.4*
  - perl=5.28.1*
  # Perl dependencies
  - libextutils-cchecker-perl=0.10*
  - libextutils-f77-perl=1.23*
  - libextutils-libbuilder-perl=0.08*
  - libextutils-pkgconfig-perl=1.16*
  - libextutils-xsbuilder-perl=0.28*
  - libextutils-xspp-perl=0.1800*
