---
- name: Ensure EPICS 7 destination path exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ epics7_base_dest }}"

- name: Unpack EPICS 7
  unarchive:
    src: "{{ epics7_base_archive }}"
    dest: "{{ epics7_base_dest }}"
    remote_src: true
    owner: root
    group: root
    creates: "{{ epics7_base_directory }}"

- name: Build EPICS 7
  make:
    chdir: "{{ epics7_base_directory }}"
    target: "{{ epics7_base_make_target | default(omit) }}"
    params: "{{ epics7_base_make_opts | default({}) }}"
  become: true
  register: build_epics_7

- name: Ensure EPICS 7 environment is installed
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.pathname }}/{{ item.filename }}"
    owner: root
    group: root
    force: true
    mode: 0644
  become: true
  with_items:
    - "{{ epics7_config_files }}"
  when: build_epics_7 is success and (epics7_add_to_system_paths | bool)
