---
# APT repositories
__repository_keys:
  - name: Debian NSLS2 key
    url: https://epicsdeb.bnl.gov/debian/repo-key.pub
    keyring: /etc/apt/trusted.gpg.d/nsls2-epics-debian.gpg

  - name: Debian Jessie 1 key
    keyserver: keyserver.ubuntu.com
    id: 9D6D8F6BC857C906

  - name: Debian Jessie 2 key
    keyserver: keyserver.ubuntu.com
    id: 8B48AD6246925553

  - name: Debian VSCode key
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/vscode-debian.gpg

__repository_apt:
  - name: NSLS2 EPICS debian repository
    baseurl: "deb https://epicsdeb.bnl.gov/debian jessie main contrib"
    description: "NSLS-II Debian EPICS repository"
    file: nsls2-epics-debian
    state: present

  - name: NSLS2 EPICS debian repository sources
    baseurl: "deb-src https://epicsdeb.bnl.gov/debian jessie main contrib"
    description: "NSLS-II Debian EPICS repository"
    file: nsls2-epics-debian-src
    state: present

  - name: Debian Jessie repository
    baseurl: "deb http://deb.debian.org/debian jessie main"
    description: "Debian Jessie repository"
    file: debian-jessie-main
    state: present

  - name: Debian Jessie repository sources
    baseurl: "deb-src http://deb.debian.org/debian jessie main"
    description: "Debian Jessie repository"
    file: debian-jessie-main-src
    state: present

  - name: Debian Jessie security repository
    baseurl: "deb http://security.debian.org/debian-security jessie/updates main"
    description: "Debian Jessie security repository"
    file: debian-jessie-updates
    state: present

  - name: Debian Jessie security repository sources
    baseurl: "deb-src http://security.debian.org/debian-security jessie/updates main"
    description: "Debian Jessie security repository"
    file: debian-jessie-updates-src
    state: present

  - name: Debian Jessie VScode
    baseurl: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    description: "Debian Jessie VScode"
    file: debian-jessie-vscode
    state: present

__apt_pinning_paths:
  - name: Pinning path for NSLS2 EPICS repository
    filename: epicsdeb-repo-pref
    pathname: "/etc/apt/preferences.d"

  - name: Pinning path for Debian Jessie repository
    filename: jessie-repo-pref
    pathname: "/etc/apt/preferences.d"
