---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install EPICS base and extra packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie
        - bullseye
    - name: Ubuntu
      versions:
        - xenial
        - trusty
  galaxy_tags:
    - development
    - octave
    - system

dependencies: []
