---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install Zabbix agent
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 2.6

  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
        - bionic

dependencies:
  - lnls-ans-role-repositories
